DnD put in a separate file.
git-svn-id: http://svn.tilp.info/repos/tilp@452

diff --git a/tilp/trunk/configure b/tilp/trunk/configure
--- a/tilp/trunk/configure
+++ b/tilp/trunk/configure
@@ -3558,23 +3558,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for ticables >= 3.7.1" >&5
-echo $ECHO_N "checking for ticables >= 3.7.1... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for ticables >= 3.8.0" >&5
+echo $ECHO_N "checking for ticables >= 3.8.0... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "ticables >= 3.7.1" ; then
+        if $PKG_CONFIG --exists "ticables >= 3.8.0" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking TICABLES_CFLAGS" >&5
 echo $ECHO_N "checking TICABLES_CFLAGS... $ECHO_C" >&6
-            TICABLES_CFLAGS=`$PKG_CONFIG --cflags "ticables >= 3.7.1"`
+            TICABLES_CFLAGS=`$PKG_CONFIG --cflags "ticables >= 3.8.0"`
             echo "$as_me:$LINENO: result: $TICABLES_CFLAGS" >&5
 echo "${ECHO_T}$TICABLES_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking TICABLES_LIBS" >&5
 echo $ECHO_N "checking TICABLES_LIBS... $ECHO_C" >&6
-            TICABLES_LIBS=`$PKG_CONFIG --libs "ticables >= 3.7.1"`
+            TICABLES_LIBS=`$PKG_CONFIG --libs "ticables >= 3.8.0"`
             echo "$as_me:$LINENO: result: $TICABLES_LIBS" >&5
 echo "${ECHO_T}$TICABLES_LIBS" >&6
         else
@@ -3582,7 +3582,7 @@ echo "${ECHO_T}$TICABLES_LIBS" >&6
             TICABLES_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            TICABLES_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "ticables >= 3.7.1"`
+            TICABLES_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "ticables >= 3.8.0"`
             echo $TICABLES_PKG_ERRORS
         fi
 
@@ -3597,8 +3597,8 @@ echo "${ECHO_T}$TICABLES_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (ticables >= 3.7.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (ticables >= 3.7.1) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (ticables >= 3.8.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (ticables >= 3.8.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -3660,23 +3660,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for tifiles >= 0.5.5" >&5
-echo $ECHO_N "checking for tifiles >= 0.5.5... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for tifiles >= 0.5.7" >&5
+echo $ECHO_N "checking for tifiles >= 0.5.7... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "tifiles >= 0.5.5" ; then
+        if $PKG_CONFIG --exists "tifiles >= 0.5.7" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking TIFILES_CFLAGS" >&5
 echo $ECHO_N "checking TIFILES_CFLAGS... $ECHO_C" >&6
-            TIFILES_CFLAGS=`$PKG_CONFIG --cflags "tifiles >= 0.5.5"`
+            TIFILES_CFLAGS=`$PKG_CONFIG --cflags "tifiles >= 0.5.7"`
             echo "$as_me:$LINENO: result: $TIFILES_CFLAGS" >&5
 echo "${ECHO_T}$TIFILES_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking TIFILES_LIBS" >&5
 echo $ECHO_N "checking TIFILES_LIBS... $ECHO_C" >&6
-            TIFILES_LIBS=`$PKG_CONFIG --libs "tifiles >= 0.5.5"`
+            TIFILES_LIBS=`$PKG_CONFIG --libs "tifiles >= 0.5.7"`
             echo "$as_me:$LINENO: result: $TIFILES_LIBS" >&5
 echo "${ECHO_T}$TIFILES_LIBS" >&6
         else
@@ -3684,7 +3684,7 @@ echo "${ECHO_T}$TIFILES_LIBS" >&6
             TIFILES_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            TIFILES_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "tifiles >= 0.5.5"`
+            TIFILES_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "tifiles >= 0.5.7"`
             echo $TIFILES_PKG_ERRORS
         fi
 
@@ -3699,8 +3699,8 @@ echo "${ECHO_T}$TIFILES_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (tifiles >= 0.5.5) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (tifiles >= 0.5.5) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (tifiles >= 0.5.7) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (tifiles >= 0.5.7) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
